import time
import pandas as pd
from typing import Any, Dict, Optional, List
from app.utils.column_mapper import find_column
from app.utils.logger import get_logger
from app.services.llm_service import get_product_relations, inferCategoryContext, classifyProductRelationship, clean_product_title

logger = get_logger("substitute_engine")

_TITLE_CANDIDATES = ["Title", "title", "Product Title"]
_BRAND_CANDIDATES = ["Brand", "brand", "Brand Name"]

def run(kc_df: Optional[pd.DataFrame], blackbox_df: Optional[pd.DataFrame], top_n: int = 10) -> Dict[str, Any]:
    t0 = time.time()
    logger.info("Substitute dataset-backed engine started.")

    if blackbox_df is None or blackbox_df.empty:
        return {"status": "error", "message": "Missing dataset."}

    title_col = find_column(blackbox_df, _TITLE_CANDIDATES)
    if not title_col: return {"status": "error", "message": "Missing BB title column."}
    
    brand_col = find_column(blackbox_df, _BRAND_CANDIDATES)
    cat_col = find_column(blackbox_df, ["Category", "Subcategory"])
    price_col = find_column(blackbox_df, ["Price", "Current Price"])

    df = blackbox_df.dropna(subset=[title_col]).copy()
    if df.empty: return {"status": "error", "message": "No valid products."}

    categoryContext = inferCategoryContext({"blackbox": blackbox_df})
    core_noun = categoryContext["main_category"]

    products = []
    
    for idx, row in df.iterrows():
        title = str(row[title_col])
        clean_title = clean_product_title(title)
        
        relationship = classifyProductRelationship(title, categoryContext)
        
        if relationship == "SUBSTITUTE_PRODUCT":
            brand = str(row[brand_col]) if brand_col and pd.notna(row[brand_col]) else "Unknown Brand"
            price = f"${row[price_col]:.2f}" if price_col and pd.notna(row[price_col]) else "N/A"
            cat = str(row[cat_col]) if cat_col and pd.notna(row[cat_col]) else "Unknown"
            
            products.append({
                "title": clean_title,
                "brand": brand,
                "reason": [
                    {"label": "Alternative Category", "value": cat},
                    {"label": "Differentiation", "value": "Solves similar need using a different product type."},
                    {"label": "Price", "value": price},
                    {"label": "Dataset-backed", "value": f"Original: {title[:50]}..."}
                ],
                "is_llm_assisted": False
            })
            if len(products) >= top_n:
                break

    if len(products) < 3:
        # Ask LLM or fallback for semantic suggestions
        suggestions = get_product_relations(core_noun, "substitute")
        for s in suggestions:
            products.append({
                "title": clean_product_title(s),
                "brand": "Conceptual Category",
                "reason": [
                    {"label": "LLM-assisted category suggestion", "value": "Semantic substitute suggestion generated by intelligence model."},
                    {"label": "Rationale", "value": "Fulfills the same customer job or use case."}
                ],
                "is_llm_assisted": True
            })

    elapsed = round(time.time() - t0, 3)
    return {
        "status": "success",
        "metric_name": "Substitute Intelligence",
        "summary": "Found conceptual or dataset-backed substitutes.",
        "results": {
            "substitute_products": products,
            "total_substitute_products": len(products),
        },
        "processing_time_seconds": elapsed,
    }
